<a href="https://colab.research.google.com/github/Crayfi/Datasets/blob/main/ArrayIssue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [ ]:
stepsForward = 3
stepsBack = 7
trainTestSplit = 0.75

In [ ]:
file = open('cannonball.csv', 'r')
df = pd.read_csv(file, error_bad_lines=False)
df_item = pd.DataFrame(df.Cannonball)

minmax = MinMaxScaler().fit(df_item.values.reshape((-1,1))[1:])
df_normalize = minmax.transform(df_item.values.reshape((-1,1))[1:])

def walk_forward(X, stepsBack, stepsForward, trainTestSplit):
  n_records = len(X)
  dfx = X[:]
  split = int(n_records*trainTestSplit-stepsForward)
  x = []
  y = []
  for i in range(n_records):
    x.append(dfx[i : i + stepsBack])  
    y.append(dfx[i + stepsBack : i + stepsBack + stepsForward])

  xtrain = x[:split]
  ytrain = y[:split]

  xtest = x[: n_records - stepsForward]
  ytest = y[: n_records - stepsForward]
	
  return np.asarray(xtrain), np.asarray(ytrain), np.asarray(xtest), np.asarray(ytest)

X_train, y_train, X_test, y_test = walk_forward(np.copy(df_normalize), stepsBack, stepsForward, trainTestSplit)

print('train=%d, test=%d' % (len(X_train), len(X_test))) 

train=2124, test=2834


/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [ ]:
X_train[:3]

array([[[0.77777778],
        [0.77777778],
        [0.77777778],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333]],

       [[0.77777778],
        [0.77777778],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333]],

       [[0.77777778],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.77777778]]])

In [ ]:
X_test[:3]

array([array([[0.77777778],
       [0.77777778],
       [0.77777778],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333]]),
       array([[0.77777778],
       [0.77777778],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333]]),
       array([[0.77777778],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.77777778]])], dtype=object)