<a href="https://colab.research.google.com/github/Crayfi/Datasets/blob/main/ArrayIssue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [4]:
stepsForward = 3
stepsBack = 7
trainTestSplit = 0.75

In [38]:
file = open('cannonball.csv', 'r')
df = pd.read_csv(file, error_bad_lines=False)
df_item = pd.DataFrame(df.Cannonball)

minmax = MinMaxScaler().fit(df_item.values.reshape((-1,1))[1:])
df_normalize = minmax.transform(df_item.values.reshape((-1,1))[1:])

def walk_forward(X, stepsBack, stepsForward, trainTestSplit):
  n_records = len(X)
  dfx = X[:]
  split = int(n_records*trainTestSplit-stepsForward)
  x = []
  y = []
  for i in range(n_records):
    x.append(dfx[i : i + stepsBack])  
    y.append(dfx[i + stepsBack : i + stepsBack + stepsForward])

  xtrain = x[:split]
  ytrain = y[:split]

  xtest = x[: n_records - stepsForward]
  ytest = y[: n_records - stepsForward]
	
  return xtrain, ytrain, xtest, ytest

X_train, y_train, X_test, y_test = walk_forward(df_normalize, stepsBack, stepsForward, trainTestSplit)

print('train=%d, test=%d' % (len(X_train), len(X_test))) 

train=2124, test=2834


In [40]:
np.array(X_train)[:3]

array([[[0.77777778],
        [0.77777778],
        [0.77777778],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333]],

       [[0.77777778],
        [0.77777778],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333]],

       [[0.77777778],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.83333333],
        [0.77777778]]])

In [41]:
np.array(X_test)[:3]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([array([[0.77777778],
       [0.77777778],
       [0.77777778],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333]]),
       array([[0.77777778],
       [0.77777778],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333]]),
       array([[0.77777778],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.83333333],
       [0.77777778]])], dtype=object)

In [42]:
np.array(y_train)[:3]

array([[[0.83333333],
        [0.77777778],
        [0.77777778]],

       [[0.77777778],
        [0.77777778],
        [0.77777778]],

       [[0.77777778],
        [0.77777778],
        [0.77777778]]])

In [43]:
np.array(y_test)[:3]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([array([[0.83333333],
       [0.77777778],
       [0.77777778]]),
       array([[0.77777778],
       [0.77777778],
       [0.77777778]]),
       array([[0.77777778],
       [0.77777778],
       [0.77777778]])], dtype=object)